disabled_rules:
   - line_length
   - type_body_length
   - identifier_name
   - multiple_closures_with_trailing_closure
   - type_name
   - trailing_whitespace
   - colon
   - cyclomatic_complexity
excluded:
   - Pods
   - fastlane
   - TestGitHubProj-HubTests
   - TestGitHubProj-HubUITests

file_length:
    warning: 500
